services:
  registry:
    container_name: registry
    image: eclipsebasyx/aas-registry:1.4.0
    ports:
        - 4000:4000
    environment:
        - basyxregistry_registry_backend=InMemory
        - basyxcontext_contextpath=/registry
        - basyxcontext_contextport=4000
        - basyxcontext_accesscontrolalloworigin=*
    networks:
      - basyx

  aas-ha-952019000082-212028000092:
    image: eclipsebasyx/aas-server:1.5.0
    container_name: ha-952019000082-212028000092
    ports:
        - 4001:4001
    volumes:
        - ./aasx:/aasx
        - ./assets:/tmp/basyx-temp
    environment:
        - basyxaas_registry_path=http://registry:4000/registry/
        - basyxaas_aas_backend=InMemory
        - basyxcontext_contextpath=/aasServer
        - basyxcontext_contextport=4001
        - waiting_for=[{"host":"registry","port":"4000"}]
        - basyxcontext_accesscontrolalloworigin=*
        - basyxaas_aas_source=["/aasx/952019000082-212028000092.json"]
    networks:
      - basyx

  aas-mccip:
    image: eclipsebasyx/aas-server:1.5.0
    container_name: aas-mccip
    ports:
        - 4002:4002
    volumes:
        - ./aasx:/aasx
        - ./assets:/tmp/basyx-temp
    environment:
        - basyxaas_registry_path=http://registry:4000/registry/
        - basyxaas_aas_backend=InMemory
        - basyxcontext_contextpath=/aasServer
        - basyxcontext_contextport=4002
        - waiting_for=[{"host":"registry","port":"4000"}]
        - basyxcontext_accesscontrolalloworigin=*
        - basyxaas_aas_source=["/aasx/mcc_ip.json"]
    networks:
      - basyx

  aas-xyz:
    image: eclipsebasyx/aas-server:1.5.0
    container_name: aas-xyz
    ports:
        - 4003:4003
    volumes:
        - ./aasx:/aasx
        - ./assets:/tmp/basyx-temp
    environment:
        - basyxaas_registry_path=http://registry:4000/registry/
        - basyxaas_aas_backend=InMemory
        - basyxcontext_contextpath=/aasServer
        - basyxcontext_contextport=4003
        - waiting_for=[{"host":"registry","port":"4000"}]
        - basyxcontext_accesscontrolalloworigin=*
        - basyxaas_aas_source=["/aasx/xyz.json"]
    networks:
      - basyx

  gui: 
    image: eclipsebasyx/aas-gui:v230703
    container_name: simple-deployment-aasGui 
    ports:
        - 3000:3000
    environment:
        -  VITE_REGISTRY_PATH="http://localhost:4000/registry"
    networks:
      - basyx

  mqtt:
    image: eclipse-mosquitto:2.0.15
    container_name: basyx-mqtt
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto:/mosquitto/config
    healthcheck:
      test: ["CMD-SHELL", mosquitto_sub -p 1883 -t 'topic' -C 1 -E -i probe -W 3]
      interval: 5s
      retries: 3
      start_period: 1s
      timeout: 10s
    networks:
      - basyx
  
  databridge:
    image: eclipsebasyx/databridge:1.0.0-milestone-06
    container_name: databridge-device-integration
    volumes:
      - ./databridge:/usr/share/config
    depends_on:
      mqtt:
        condition: service_healthy
    networks:
      - basyx


networks:
  basyx:
    name: basyx-net