services:
  registry:
    container_name: registry
    image: eclipsebasyx/aas-registry:1.4.0
    ports:
        - 4000:4000
    environment:
        - basyxregistry_registry_backend=InMemory
        - basyxcontext_contextpath=/registry
        - basyxcontext_contextport=4000
        - basyxcontext_accesscontrolalloworigin=*

  aas-ha-952019000082-212028000092:
    image: eclipsebasyx/aas-server:1.5.0
    container_name: ha-952019000082-212028000092
    ports:
        - 4001:4001
    volumes:
        - ./aasx:/aasx
        - ./assets:/tmp/basyx-temp
    environment:
        - basyxaas_registry_path=http://registry:4000/registry/
        - basyxaas_aas_backend=InMemory
        - basyxcontext_contextpath=/aasServer
        - basyxcontext_contextport=4001
        - waiting_for=[{"host":"registry","port":"4000"}]
        - basyxcontext_accesscontrolalloworigin=*
        - basyxaas_aas_source=["/aasx/952019000082-212028000092.json"]

  aas-mccip:
    image: eclipsebasyx/aas-server:1.5.0
    container_name: aas-mccip
    ports:
        - 4002:4002
    volumes:
        - ./aasx:/aasx
        - ./assets:/tmp/basyx-temp
    environment:
        - basyxaas_registry_path=http://registry:4000/registry/
        - basyxaas_aas_backend=InMemory
        - basyxcontext_contextpath=/aasServer
        - basyxcontext_contextport=4002
        - waiting_for=[{"host":"registry","port":"4000"}]
        - basyxcontext_accesscontrolalloworigin=*
        - basyxaas_aas_source=["/aasx/mcc_ip.json"]

  aas-xyz:
    image: eclipsebasyx/aas-server:1.5.0
    container_name: aas-xyz
    ports:
        - 4003:4003
    volumes:
        - ./aasx:/aasx
        - ./assets:/tmp/basyx-temp
    environment:
        - basyxaas_registry_path=http://registry:4000/registry/
        - basyxaas_aas_backend=InMemory
        - basyxcontext_contextpath=/aasServer
        - basyxcontext_contextport=4003
        - waiting_for=[{"host":"registry","port":"4000"}]
        - basyxcontext_accesscontrolalloworigin=*
        - basyxaas_aas_source=["/aasx/xyz.json"]

  gui: 
    image: eclipsebasyx/aas-gui:v230703
    container_name: simple-deployment-aasGui 
    ports:
        - 3000:3000
    environment:
        -  VITE_REGISTRY_PATH="http://localhost:4000/registry"
